version: '3'

services:
  test_monitor:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - RUN_TESTS=${RUN_TESTS:-false}  # Default to false if not set
    command: python app.py
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://test_monitor:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      test_monitor:
        condition: service_healthy
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    environment:
      - RUN_TESTS=${RUN_TESTS:-true}  # Default to true if not set
    command: >
      sh -c "if [ '${RUN_TESTS}' = 'true' ]; then pytest tests/ --alluredir=/app/allure-results; fi"
    networks:
      - app-network

  allure:
    image: frankescobar/allure-docker-service
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/allure-reports
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
